[package]
name = "crude"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
fern = "0.7.1"
humantime = "2.1.0"
log = "0.4.25"
zerocopy = "0.8.17"

[workspace]
members = [
"dbg"
]
resolver = "2"
